#!/usr/bin/env bash

if [ $# -ge 1 ] && [ -n "$1" ]; then
    FINDER=$1
else
    FINDER=fzf
fi

RESULT=$(op item list --format=json | jq -r ".[].title" | $FINDER)

if [ -n "$RESULT" ]; then
    PASS=$(op item get "$RESULT" --fields password --reveal)
    wl-copy "$PASS"
fi
