#!/usr/bin/env bash

if ! rbw unlocked; then
    if ! rbw unlock; then
        exit
    fi
fi

if [ $# -ge 1 ] && [ -n "$1" ]; then
    FINDER=$1
else
    FINDER=fzf
fi

RESULT=$(rbw list | $FINDER)

if [ -n "$RESULT" ]; then
    PASS=$(rbw get "$RESULT")
    wl-copy "$PASS"
fi
