session_name: Nix Config
start_directory: ~/nix-config/
windows:
  - window_name: Code
    panes:
      - shell_command:
          - nvim
        focus: true
  - window_name: Terminal
    panes:
      - shell_command:
  - window_name: Git
    panes:
      - shell_command:
          - gitui
