[mgr]
syntect_theme = "~/.config/bat/themes/base16.tmTheme"

[mgr.border_style]
fg = "DarkGray"

[mgr.count_copied]
bg = "Green"
fg = "Black"

[mgr.count_cut]
bg = "Red"
fg = "Black"

[mgr.count_selected]
bg = "Yellow"
fg = "Black"

[mgr.cwd]
fg = "Yellow"

[mode.normal_alt]
bg = "DarkGray"
fg = "Black"

[mode.normal_main]
bg = "Blue"
bold = true
fg = "Black"

[mode.select_alt]
bg = "DarkGray"
fg = "Black"

[mode.select_main]
bg = "Green"
bold = true
fg = "Black"

[mode.unset_alt]
bg = "DarkGray"
fg = "Black"

[mode.unset_main]
bg = "Yellow"
bold = true
fg = "Black"

[status.overall]
bg = "Black"
fg = "White"
