#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [[ $# -eq 0 ]]; then
    nixos-rebuild --help
    exit 0
fi

HOSTNAME="$(hostname)"
echo -e "Running nixos-rebuild \e[1;33m$1\e[0m for host \e[1;36m$HOSTNAME\e[0m ..."
nixos-rebuild "$1" --file . -A "hosts.$HOSTNAME" --no-reexec --sudo

# Update all flatpaks if flatpak is installed
if command -v flatpak >/dev/null 2>&1; then
    flatpak update
fi
