#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    RESULT=$(find ./*.md | fzf) || true
else
    RESULT=$1
fi

if [ -n "$RESULT" ]; then
    lowdown -tterm "$RESULT" --term-columns 120 --term-hmargin 4 --term-vmargin 1 --term-shortlinks | less -R
fi
