require("plugins.fzf-lua")
require("plugins.treesitter")
require("plugins.blink")
require("plugins.gitsigns")
require("plugins.heirline")
require("plugins.lsp")

require("nvim-autopairs").setup()
require("Comment").setup()
require("ibl").setup()
require("nvim-surround").setup()
require("colorizer").setup()

require("plugins.which-key")
require("plugins.render-markdown")
